// AUTO-GENERATED by scripts/fetch-exercise-media.ts. Do not edit by hand.
// Regenerate with: npm run media:fetch

export type ExerciseMedia = {
  name: string
  slug: string
  frames: string[]
  instructions: string[]
  primaryMuscles: string[]
}

export const EXERCISE_MEDIA: Record<string, ExerciseMedia> = {
  "4-way neck isometric": {
    "name": "4-way neck isometric",
    "slug": "4-way-neck-isometric",
    "frames": [
      "/exercise-media/4-way-neck-isometric/0.jpg",
      "/exercise-media/4-way-neck-isometric/1.jpg"
    ],
    "instructions": [
      "With your head and neck in a neutral position (normal position with head erect facing forward), place both of your hands on the front side of your head.",
      "Now gently push forward as you contract the neck muscles but resisting any movement of your head. Start with slow tension and increase slowly. Keep breathing normally as you execute this contraction.",
      "Hold for the recommended number of seconds.",
      "Now release the tension slowly.",
      "Rest for the recommended amount of time and repeat with your hands placed on the back side of your head."
    ],
    "primaryMuscles": [
      "neck"
    ]
  },
  "bulgarian split squat": {
    "name": "Bulgarian split squat",
    "slug": "bulgarian-split-squat",
    "frames": [
      "/exercise-media/bulgarian-split-squat/0.jpg",
      "/exercise-media/bulgarian-split-squat/1.jpg"
    ],
    "instructions": [
      "Position yourself into a staggered stance with the rear foot elevated and front foot forward.",
      "Hold a dumbbell in each hand, letting them hang at the sides. This will be your starting position.",
      "Begin by descending, flexing your knee and hip to lower your body down. Maintain good posture througout the movement. Keep the front knee in line with the foot as you perform the exercise.",
      "At the bottom of the movement, drive through the heel to extend the knee and hip to return to the starting position."
    ],
    "primaryMuscles": [
      "quadriceps"
    ]
  },
  "carry or crawl finisher": {
    "name": "Carry or crawl finisher",
    "slug": "carry-or-crawl-finisher",
    "frames": [
      "/exercise-media/carry-or-crawl-finisher/0.jpg",
      "/exercise-media/carry-or-crawl-finisher/1.jpg"
    ],
    "instructions": [
      "Position the frame at the starting point, and load with the appropriate weight. Standing in the center of the frame, begin by gripping the handles and driving through your heels to lift the frame. Ensure your chest and head are up and your back is straight.",
      "Immediately begin walking briskly with quick, controlled steps. Keep your chest up and head forward, and make sure you continue breathing. Bring the frame to the ground after you have reached the end point."
    ],
    "primaryMuscles": [
      "forearms"
    ]
  },
  "carry or neck circuit": {
    "name": "Carry or neck circuit",
    "slug": "carry-or-neck-circuit",
    "frames": [
      "/exercise-media/carry-or-neck-circuit/0.jpg",
      "/exercise-media/carry-or-neck-circuit/1.jpg"
    ],
    "instructions": [
      "Position the frame at the starting point, and load with the appropriate weight. Standing in the center of the frame, begin by gripping the handles and driving through your heels to lift the frame. Ensure your chest and head are up and your back is straight.",
      "Immediately begin walking briskly with quick, controlled steps. Keep your chest up and head forward, and make sure you continue breathing. Bring the frame to the ground after you have reached the end point."
    ],
    "primaryMuscles": [
      "forearms"
    ]
  },
  "chest-supported row": {
    "name": "Chest-supported row",
    "slug": "chest-supported-row",
    "frames": [
      "/exercise-media/chest-supported-row/0.jpg",
      "/exercise-media/chest-supported-row/1.jpg"
    ],
    "instructions": [
      "Using a neutral grip, lean into an incline bench.",
      "Take a dumbbell in each hand with a neutral grip, beginning with the arms straight. This will be your starting position.",
      "Retract the shoulder blades and flex the elbows to row the dumbbells to your side.",
      "Pause at the top of the motion, and then return to the starting position."
    ],
    "primaryMuscles": [
      "middle back"
    ]
  },
  "close-grip bench press": {
    "name": "Close-grip bench press",
    "slug": "close-grip-bench-press",
    "frames": [
      "/exercise-media/close-grip-bench-press/0.jpg",
      "/exercise-media/close-grip-bench-press/1.jpg"
    ],
    "instructions": [
      "Lie back on a flat bench. Using a close grip (around shoulder width), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
      "As you breathe in, come down slowly until you feel the bar on your middle chest. Tip: Make sure that - as opposed to a regular bench press - you keep the elbows close to the torso at all times in order to maximize triceps involvement.",
      "After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your triceps muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.",
      "Repeat the movement for the prescribed amount of repetitions.",
      "When you are done, place the bar back in the rack."
    ],
    "primaryMuscles": [
      "triceps"
    ]
  },
  "copenhagen plank": {
    "name": "Copenhagen plank",
    "slug": "copenhagen-plank",
    "frames": [
      "/exercise-media/copenhagen-plank/0.jpg",
      "/exercise-media/copenhagen-plank/1.jpg"
    ],
    "instructions": [
      "Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.",
      "Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised."
    ],
    "primaryMuscles": [
      "abdominals"
    ]
  },
  "easy med-ball throw": {
    "name": "Easy med-ball throw",
    "slug": "easy-med-ball-throw",
    "frames": [
      "/exercise-media/easy-med-ball-throw/0.jpg",
      "/exercise-media/easy-med-ball-throw/1.jpg"
    ],
    "instructions": [
      "Assume a semisquat stance with a medicine ball in your hands. Your arms should hang so the ball is near your feet.",
      "Begin by thrusting the hips forward as you extend through the legs, jumping up.",
      "As you do, swing your arms up and over your head, keeping them extended, releasing the ball at the peak of your movement. The goal is to throw the ball the greatest distance behind you."
    ],
    "primaryMuscles": [
      "shoulders"
    ]
  },
  "flat db press": {
    "name": "Flat DB press",
    "slug": "flat-db-press",
    "frames": [
      "/exercise-media/flat-db-press/0.jpg",
      "/exercise-media/flat-db-press/1.jpg"
    ],
    "instructions": [
      "Lie down on a flat bench with a dumbbell in each hand resting on top of your thighs. The palms of your hands will be facing each other.",
      "Then, using your thighs to help raise the dumbbells up, lift the dumbbells one at a time so that you can hold them in front of you at shoulder width.",
      "Once at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. The dumbbells should be just to the sides of your chest, with your upper arm and forearm creating a 90 degree angle. Be sure to maintain full control of the dumbbells at all times. This will be your starting position.",
      "Then, as you breathe out, use your chest to push the dumbbells up. Lock your arms at the top of the lift and squeeze your chest, hold for a second and then begin coming down slowly. Tip: Ideally, lowering the weight should take about twice as long as raising it.",
      "Repeat the movement for the prescribed amount of repetitions of your training program."
    ],
    "primaryMuscles": [
      "chest"
    ]
  },
  "front squat": {
    "name": "Front squat",
    "slug": "front-squat",
    "frames": [
      "/exercise-media/front-squat/0.jpg",
      "/exercise-media/front-squat/1.jpg"
    ],
    "instructions": [
      "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, bring your arms up under the bar while keeping the elbows high and the upper arm slightly above parallel to the floor. Rest the bar on top of the deltoids and cross your arms while grasping the bar for total control.",
      "Lift the bar off the rack by first pushing with your legs and at the same time straightening your torso.",
      "Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).",
      "Begin to slowly lower the bar by bending the knees as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.",
      "Begin to raise the bar as you exhale by pushing the floor mainly with the middle of your foot as you straighten the legs again and go back to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "quadriceps"
    ]
  },
  "front squat speed sets": {
    "name": "Front squat speed sets",
    "slug": "front-squat-speed-sets",
    "frames": [
      "/exercise-media/front-squat-speed-sets/0.jpg",
      "/exercise-media/front-squat-speed-sets/1.jpg"
    ],
    "instructions": [
      "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, bring your arms up under the bar while keeping the elbows high and the upper arm slightly above parallel to the floor. Rest the bar on top of the deltoids and cross your arms while grasping the bar for total control.",
      "Lift the bar off the rack by first pushing with your legs and at the same time straightening your torso.",
      "Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).",
      "Begin to slowly lower the bar by bending the knees as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.",
      "Begin to raise the bar as you exhale by pushing the floor mainly with the middle of your foot as you straighten the legs again and go back to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "quadriceps"
    ]
  },
  "hamstring curl": {
    "name": "Hamstring curl",
    "slug": "hamstring-curl",
    "frames": [
      "/exercise-media/hamstring-curl/0.jpg",
      "/exercise-media/hamstring-curl/1.jpg"
    ],
    "instructions": [
      "Adjust the machine lever to fit your height and lie face down on the leg curl machine with the pad of the lever on the back of your legs (just a few inches under the calves). Tip: Preferably use a leg curl machine that is angled as opposed to flat since an angled position is more favorable for hamstrings recruitment.",
      "Keeping the torso flat on the bench, ensure your legs are fully stretched and grab the side handles of the machine. Position your toes straight (or you can also use any of the other two stances described on the foot positioning section). This will be your starting position.",
      "As you exhale, curl your legs up as far as possible without lifting the upper legs from the pad. Once you hit the fully contracted position, hold it for a second.",
      "As you inhale, bring the legs back to the initial position. Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "hamstrings"
    ]
  },
  "hamstring curl or copenhagen": {
    "name": "Hamstring curl or Copenhagen",
    "slug": "hamstring-curl-or-copenhagen",
    "frames": [
      "/exercise-media/hamstring-curl-or-copenhagen/0.jpg",
      "/exercise-media/hamstring-curl-or-copenhagen/1.jpg"
    ],
    "instructions": [
      "Adjust the machine lever to fit your height and lie face down on the leg curl machine with the pad of the lever on the back of your legs (just a few inches under the calves). Tip: Preferably use a leg curl machine that is angled as opposed to flat since an angled position is more favorable for hamstrings recruitment.",
      "Keeping the torso flat on the bench, ensure your legs are fully stretched and grab the side handles of the machine. Position your toes straight (or you can also use any of the other two stances described on the foot positioning section). This will be your starting position.",
      "As you exhale, curl your legs up as far as possible without lifting the upper legs from the pad. Once you hit the fully contracted position, hold it for a second.",
      "As you inhale, bring the legs back to the initial position. Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "hamstrings"
    ]
  },
  "hamstring curl or nordic regression": {
    "name": "Hamstring curl or Nordic regression",
    "slug": "hamstring-curl-or-nordic-regression",
    "frames": [
      "/exercise-media/hamstring-curl-or-nordic-regression/0.jpg",
      "/exercise-media/hamstring-curl-or-nordic-regression/1.jpg"
    ],
    "instructions": [
      "Adjust the machine lever to fit your height and lie face down on the leg curl machine with the pad of the lever on the back of your legs (just a few inches under the calves). Tip: Preferably use a leg curl machine that is angled as opposed to flat since an angled position is more favorable for hamstrings recruitment.",
      "Keeping the torso flat on the bench, ensure your legs are fully stretched and grab the side handles of the machine. Position your toes straight (or you can also use any of the other two stances described on the foot positioning section). This will be your starting position.",
      "As you exhale, curl your legs up as far as possible without lifting the upper legs from the pad. Once you hit the fully contracted position, hold it for a second.",
      "As you inhale, bring the legs back to the initial position. Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "hamstrings"
    ]
  },
  "hang high pull or jump shrug": {
    "name": "Hang high pull or jump shrug",
    "slug": "hang-high-pull-or-jump-shrug",
    "frames": [
      "/exercise-media/hang-high-pull-or-jump-shrug/0.jpg",
      "/exercise-media/hang-high-pull-or-jump-shrug/1.jpg"
    ],
    "instructions": [
      "Place a kettlebell on the ground between your feet. Position your feet in a wide stance, and grasp the kettlebell with two hands. Set your hips back as far as possible, with your knees bent. Keep your chest and head up. This will be your starting position.",
      "Begin by extending the hips and knees, simultaneously pulling the kettlebell to your shoulders, raising your elbows as you do so. Reverse the motion to return to the starting position."
    ],
    "primaryMuscles": [
      "traps"
    ]
  },
  "hinge or posterior chain": {
    "name": "Hinge or posterior chain",
    "slug": "hinge-or-posterior-chain",
    "frames": [
      "/exercise-media/hinge-or-posterior-chain/0.jpg",
      "/exercise-media/hinge-or-posterior-chain/1.jpg"
    ],
    "instructions": [
      "Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion.",
      "Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position.",
      "Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control.",
      "Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "hamstrings"
    ]
  },
  "jump primer": {
    "name": "Jump primer",
    "slug": "jump-primer",
    "frames": [
      "/exercise-media/jump-primer/0.jpg",
      "/exercise-media/jump-primer/1.jpg"
    ],
    "instructions": [
      "Cross your arms over your chest.",
      "With your head up and your back straight, position your feet at shoulder width.",
      "Keeping your back straight and chest up, squat down as you inhale until your upper thighs are parallel, or lower, to the floor.",
      "Now pressing mainly with the ball of your feet, jump straight up in the air as high as possible, using the thighs like springs. Exhale during this portion of the movement.",
      "When you touch the floor again, immediately squat down and jump again.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "quadriceps"
    ]
  },
  "landmine rotation": {
    "name": "Landmine rotation",
    "slug": "landmine-rotation",
    "frames": [
      "/exercise-media/landmine-rotation/0.jpg",
      "/exercise-media/landmine-rotation/1.jpg"
    ],
    "instructions": [
      "Position a bar into a landmine or securely anchor it in a corner. Load the bar to an appropriate weight.",
      "Raise the bar from the floor, taking it to shoulder height with both hands with your arms extended in front of you. Adopt a wide stance. This will be your starting position.",
      "Perform the movement by rotating the trunk and hips as you swing the weight all the way down to one side. Keep your arms extended throughout the exercise.",
      "Reverse the motion to swing the weight all the way to the opposite side.",
      "Continue alternating the movement until the set is complete."
    ],
    "primaryMuscles": [
      "abdominals"
    ]
  },
  "light carry or mobility circuit": {
    "name": "Light carry or mobility circuit",
    "slug": "light-carry-or-mobility-circuit",
    "frames": [
      "/exercise-media/light-carry-or-mobility-circuit/0.jpg",
      "/exercise-media/light-carry-or-mobility-circuit/1.jpg"
    ],
    "instructions": [
      "Position the frame at the starting point, and load with the appropriate weight. Standing in the center of the frame, begin by gripping the handles and driving through your heels to lift the frame. Ensure your chest and head are up and your back is straight.",
      "Immediately begin walking briskly with quick, controlled steps. Keep your chest up and head forward, and make sure you continue breathing. Bring the frame to the ground after you have reached the end point."
    ],
    "primaryMuscles": [
      "forearms"
    ]
  },
  "low-incline barbell press": {
    "name": "Low-incline barbell press",
    "slug": "low-incline-barbell-press",
    "frames": [
      "/exercise-media/low-incline-barbell-press/0.jpg",
      "/exercise-media/low-incline-barbell-press/1.jpg"
    ],
    "instructions": [
      "Lie back on an incline bench. Using a medium-width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
      "As you breathe in, come down slowly until you feel the bar on you upper chest.",
      "After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms in the contracted position, squeeze your chest, hold for a second and then start coming down slowly again. Tip: it should take at least twice as long to go down than to come up.",
      "Repeat the movement for the prescribed amount of repetitions.",
      "When you are done, place the bar back in the rack."
    ],
    "primaryMuscles": [
      "chest"
    ]
  },
  "low-incline press": {
    "name": "Low-incline press",
    "slug": "low-incline-press",
    "frames": [
      "/exercise-media/low-incline-press/0.jpg",
      "/exercise-media/low-incline-press/1.jpg"
    ],
    "instructions": [
      "Lie back on an incline bench. Using a medium-width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
      "As you breathe in, come down slowly until you feel the bar on you upper chest.",
      "After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms in the contracted position, squeeze your chest, hold for a second and then start coming down slowly again. Tip: it should take at least twice as long to go down than to come up.",
      "Repeat the movement for the prescribed amount of repetitions.",
      "When you are done, place the bar back in the rack."
    ],
    "primaryMuscles": [
      "chest"
    ]
  },
  "main squat pattern": {
    "name": "Main squat pattern",
    "slug": "main-squat-pattern",
    "frames": [
      "/exercise-media/main-squat-pattern/0.jpg",
      "/exercise-media/main-squat-pattern/1.jpg"
    ],
    "instructions": [
      "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack to just below shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.",
      "Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.",
      "Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances discussed in the foot stances section).",
      "Begin to slowly lower the bar by bending the knees and hips as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees. Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.",
      "Begin to raise the bar as you exhale by pushing the floor with the heel of your foot as you straighten the legs again and go back to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "quadriceps"
    ]
  },
  "neck work": {
    "name": "Neck work",
    "slug": "neck-work",
    "frames": [
      "/exercise-media/neck-work/0.jpg",
      "/exercise-media/neck-work/1.jpg"
    ],
    "instructions": [
      "With your head and neck in a neutral position (normal position with head erect facing forward), place both of your hands on the front side of your head.",
      "Now gently push forward as you contract the neck muscles but resisting any movement of your head. Start with slow tension and increase slowly. Keep breathing normally as you execute this contraction.",
      "Hold for the recommended number of seconds.",
      "Now release the tension slowly.",
      "Rest for the recommended amount of time and repeat with your hands placed on the back side of your head."
    ],
    "primaryMuscles": [
      "neck"
    ]
  },
  "neutral-grip pulldown": {
    "name": "Neutral-grip pulldown",
    "slug": "neutral-grip-pulldown",
    "frames": [
      "/exercise-media/neutral-grip-pulldown/0.jpg",
      "/exercise-media/neutral-grip-pulldown/1.jpg"
    ],
    "instructions": [
      "Sit down on a pull-down machine with a V-Bar attached to the top pulley.",
      "Adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.",
      "Grab the V-bar with the palms facing each other (a neutral grip). Stick your chest out and lean yourself back slightly (around 30-degrees) in order to better engage the lats. This will be your starting position.",
      "Using your lats, pull the bar down as you squeeze your shoulder blades. Continue until your chest nearly touches the V-bar. Exhale as you execute this motion. Tip: Keep the torso stationary throughout the movement.",
      "After a second hold on the contracted position, slowly bring the bar back to the starting position as you breathe in.",
      "Repeat for the prescribed number of repetitions."
    ],
    "primaryMuscles": [
      "lats"
    ]
  },
  "neutral-grip pulldown or chin-up": {
    "name": "Neutral-grip pulldown or chin-up",
    "slug": "neutral-grip-pulldown-or-chin-up",
    "frames": [
      "/exercise-media/neutral-grip-pulldown-or-chin-up/0.jpg",
      "/exercise-media/neutral-grip-pulldown-or-chin-up/1.jpg"
    ],
    "instructions": [
      "Sit down on a pull-down machine with a V-Bar attached to the top pulley.",
      "Adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.",
      "Grab the V-bar with the palms facing each other (a neutral grip). Stick your chest out and lean yourself back slightly (around 30-degrees) in order to better engage the lats. This will be your starting position.",
      "Using your lats, pull the bar down as you squeeze your shoulder blades. Continue until your chest nearly touches the V-bar. Exhale as you execute this motion. Tip: Keep the torso stationary throughout the movement.",
      "After a second hold on the contracted position, slowly bring the bar back to the starting position as you breathe in.",
      "Repeat for the prescribed number of repetitions."
    ],
    "primaryMuscles": [
      "lats"
    ]
  },
  "one-arm cable row or seal row": {
    "name": "One-arm cable row or seal row",
    "slug": "one-arm-cable-row-or-seal-row",
    "frames": [
      "/exercise-media/one-arm-cable-row-or-seal-row/0.jpg",
      "/exercise-media/one-arm-cable-row-or-seal-row/1.jpg"
    ],
    "instructions": [
      "To get into the starting position, first sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked.",
      "Lean over as you keep the natural alignment of your back and grab the single handle attachment with your left arm using a palms-down grip.",
      "With your arm extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. You should be feeling a nice stretch on your lat as you hold the bar in front of you. The right arm can be kept by the waist. This is the starting position of the exercise.",
      "Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it as you rotate the wrist, so that by the time your hand is by your abdominals it is in a neutral position (palms facing the torso). Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard.",
      "Hold that contraction for a second and slowly go back to the original position while breathing in. Tip: Remember to rotate the wrist as you go back to the starting position so that the palms are facing down again.",
      "Repeat for the recommended amount of repetitions and then perform the same movement with the right hand."
    ],
    "primaryMuscles": [
      "middle back"
    ]
  },
  "overhead rear throw": {
    "name": "Overhead rear throw",
    "slug": "overhead-rear-throw",
    "frames": [
      "/exercise-media/overhead-rear-throw/0.jpg",
      "/exercise-media/overhead-rear-throw/1.jpg"
    ],
    "instructions": [
      "This exercise is best done with a partner. If you lack a partner, the ball can be thrown and retrieved or thrown against a wall.",
      "Begin standing a few meters in front of your partner, both facing the same direction. Begin holding the ball between your legs.",
      "Squat down and then forcefully reverse direction, coming to full extension and you toss the ball over your head to your partner.",
      "Your partner can then roll the ball back to you. Repeat for the desired number of repetitions."
    ],
    "primaryMuscles": [
      "shoulders"
    ]
  },
  "pallof press": {
    "name": "Pallof press",
    "slug": "pallof-press",
    "frames": [
      "/exercise-media/pallof-press/0.jpg",
      "/exercise-media/pallof-press/1.jpg"
    ],
    "instructions": [
      "Connect a standard handle to a tower, and—if possible—position the cable to shoulder height. If not, a low pulley will suffice.",
      "With your side to the cable, grab the handle with both hands and step away from the tower. You should be approximately arm's length away from the pulley, with the tension of the weight on the cable.",
      "With your feet positioned hip-width apart and knees slightly bent, hold the cable to the middle of your chest. This will be your starting position.",
      "Press the cable away from your chest, fully extending both arms. You core should be tight and engaged.",
      "Hold the repetition for several seconds before returning to the starting position.",
      "At the conclusion of the set, repeat facing the other direction."
    ],
    "primaryMuscles": [
      "abdominals"
    ]
  },
  "pallof press or anti-rotation cable lift": {
    "name": "Pallof press or anti-rotation cable lift",
    "slug": "pallof-press-or-anti-rotation-cable-lift",
    "frames": [
      "/exercise-media/pallof-press-or-anti-rotation-cable-lift/0.jpg",
      "/exercise-media/pallof-press-or-anti-rotation-cable-lift/1.jpg"
    ],
    "instructions": [
      "Connect a standard handle to a tower, and—if possible—position the cable to shoulder height. If not, a low pulley will suffice.",
      "With your side to the cable, grab the handle with both hands and step away from the tower. You should be approximately arm's length away from the pulley, with the tension of the weight on the cable.",
      "With your feet positioned hip-width apart and knees slightly bent, hold the cable to the middle of your chest. This will be your starting position.",
      "Press the cable away from your chest, fully extending both arms. You core should be tight and engaged.",
      "Hold the repetition for several seconds before returning to the starting position.",
      "At the conclusion of the set, repeat facing the other direction."
    ],
    "primaryMuscles": [
      "abdominals"
    ]
  },
  "pallof press or suitcase carry": {
    "name": "Pallof press or suitcase carry",
    "slug": "pallof-press-or-suitcase-carry",
    "frames": [
      "/exercise-media/pallof-press-or-suitcase-carry/0.jpg",
      "/exercise-media/pallof-press-or-suitcase-carry/1.jpg"
    ],
    "instructions": [
      "Connect a standard handle to a tower, and—if possible—position the cable to shoulder height. If not, a low pulley will suffice.",
      "With your side to the cable, grab the handle with both hands and step away from the tower. You should be approximately arm's length away from the pulley, with the tension of the weight on the cable.",
      "With your feet positioned hip-width apart and knees slightly bent, hold the cable to the middle of your chest. This will be your starting position.",
      "Press the cable away from your chest, fully extending both arms. You core should be tight and engaged.",
      "Hold the repetition for several seconds before returning to the starting position.",
      "At the conclusion of the set, repeat facing the other direction."
    ],
    "primaryMuscles": [
      "abdominals"
    ]
  },
  "press pattern": {
    "name": "Press pattern",
    "slug": "press-pattern",
    "frames": [
      "/exercise-media/press-pattern/0.jpg",
      "/exercise-media/press-pattern/1.jpg"
    ],
    "instructions": [
      "Lie back on a flat bench. Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
      "From the starting position, breathe in and begin coming down slowly until the bar touches your middle chest.",
      "After a brief pause, push the bar back to the starting position as you breathe out. Focus on pushing the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position at the top of the motion, hold for a second and then start coming down slowly again. Tip: Ideally, lowering the weight should take about twice as long as raising it.",
      "Repeat the movement for the prescribed amount of repetitions.",
      "When you are done, place the bar back in the rack."
    ],
    "primaryMuscles": [
      "chest"
    ]
  },
  "pull pattern": {
    "name": "Pull pattern",
    "slug": "pull-pattern",
    "frames": [
      "/exercise-media/pull-pattern/0.jpg",
      "/exercise-media/pull-pattern/1.jpg"
    ],
    "instructions": [
      "Grab the pull-up bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.",
      "As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.",
      "Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.",
      "After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.",
      "Repeat this motion for the prescribed amount of repetitions."
    ],
    "primaryMuscles": [
      "lats"
    ]
  },
  "pulldown or row": {
    "name": "Pulldown or row",
    "slug": "pulldown-or-row",
    "frames": [
      "/exercise-media/pulldown-or-row/0.jpg",
      "/exercise-media/pulldown-or-row/1.jpg"
    ],
    "instructions": [
      "Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.",
      "Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.",
      "As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.",
      "As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms.",
      "After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.",
      "Repeat this motion for the prescribed amount of repetitions."
    ],
    "primaryMuscles": [
      "lats"
    ]
  },
  "push press": {
    "name": "Push press",
    "slug": "push-press",
    "frames": [
      "/exercise-media/push-press/0.jpg",
      "/exercise-media/push-press/1.jpg"
    ],
    "instructions": [],
    "primaryMuscles": [
      "shoulders"
    ]
  },
  "push press or push jerk": {
    "name": "Push press or push jerk",
    "slug": "push-press-or-push-jerk",
    "frames": [
      "/exercise-media/push-press-or-push-jerk/0.jpg",
      "/exercise-media/push-press-or-push-jerk/1.jpg"
    ],
    "instructions": [],
    "primaryMuscles": [
      "shoulders"
    ]
  },
  "push press technique": {
    "name": "Push press technique",
    "slug": "push-press-technique",
    "frames": [
      "/exercise-media/push-press-technique/0.jpg",
      "/exercise-media/push-press-technique/1.jpg"
    ],
    "instructions": [],
    "primaryMuscles": [
      "shoulders"
    ]
  },
  "romanian deadlift": {
    "name": "Romanian deadlift",
    "slug": "romanian-deadlift",
    "frames": [
      "/exercise-media/romanian-deadlift/0.jpg",
      "/exercise-media/romanian-deadlift/1.jpg"
    ],
    "instructions": [
      "Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion.",
      "Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position.",
      "Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control.",
      "Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "hamstrings"
    ]
  },
  "rotational scoop toss": {
    "name": "Rotational scoop toss",
    "slug": "rotational-scoop-toss",
    "frames": [
      "/exercise-media/rotational-scoop-toss/0.jpg",
      "/exercise-media/rotational-scoop-toss/1.jpg"
    ],
    "instructions": [
      "Assume a semisquat stance with a medicine ball in your hands. Your arms should hang so the ball is near your feet.",
      "Begin by thrusting the hips forward as you extend through the legs, jumping up.",
      "As you do, swing your arms up and over your head, keeping them extended, releasing the ball at the peak of your movement. The goal is to throw the ball the greatest distance behind you."
    ],
    "primaryMuscles": [
      "shoulders"
    ]
  },
  "rotational shot-put throw": {
    "name": "Rotational shot-put throw",
    "slug": "rotational-shot-put-throw",
    "frames": [
      "/exercise-media/rotational-shot-put-throw/0.jpg",
      "/exercise-media/rotational-shot-put-throw/1.jpg"
    ],
    "instructions": [
      "Assume a semisquat stance with a medicine ball in your hands. Your arms should hang so the ball is near your feet.",
      "Begin by thrusting the hips forward as you extend through the legs, jumping up.",
      "As you do, swing your arms up and over your head, keeping them extended, releasing the ball at the peak of your movement. The goal is to throw the ball the greatest distance behind you."
    ],
    "primaryMuscles": [
      "shoulders"
    ]
  },
  "row or pulldown": {
    "name": "Row or pulldown",
    "slug": "row-or-pulldown",
    "frames": [
      "/exercise-media/row-or-pulldown/0.jpg",
      "/exercise-media/row-or-pulldown/1.jpg"
    ],
    "instructions": [
      "Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.",
      "Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.",
      "Then inhale and slowly lower the barbell back to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "middle back"
    ]
  },
  "seal row": {
    "name": "Seal row",
    "slug": "seal-row",
    "frames": [
      "/exercise-media/seal-row/0.jpg",
      "/exercise-media/seal-row/1.jpg"
    ],
    "instructions": [
      "Load up the T-bar Row Machine with the desired weight and adjust the leg height so that your upper chest is at the top of the pad. Tip: In some machines all you can do is stand on the appropriate step that allows you to be at a height that has the upper chest at the top of the pad.",
      "Lay face down on the pad and grab the handles. You can either use a palms down, palms up, or palms in position depending on what part of your back you want to emphasize.",
      "Lift the bar off the rack and extend your arms in front of you. This will be your starting position.",
      "As you exhale slowly pull the weight up and squeeze your back at the top of the movement. Tip: Keep the upper arms as close to the torso as possible throughout the movement in order to better engage the back muscles. Also, do not lift your body off of the pad at any time and refrain from using the biceps to lift the weight.",
      "After a second contraction at the top of the movement, as you inhale, slowly go back down to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "middle back"
    ]
  },
  "sled drag or rope drag": {
    "name": "Sled drag or rope drag",
    "slug": "sled-drag-or-rope-drag",
    "frames": [
      "/exercise-media/sled-drag-or-rope-drag/0.jpg",
      "/exercise-media/sled-drag-or-rope-drag/1.jpg"
    ],
    "instructions": [
      "To begin, load the sled with the desired weight and attach the pulling strap. You can pull with handles, use a harness, or attach the pulling strap to a weight belt.",
      "Whether pulling forwards or backwards, lean in the direction of travel and progress by extending through the hips and knees."
    ],
    "primaryMuscles": [
      "quadriceps"
    ]
  },
  "step-in shot-put throw": {
    "name": "Step-in shot-put throw",
    "slug": "step-in-shot-put-throw",
    "frames": [
      "/exercise-media/step-in-shot-put-throw/0.jpg",
      "/exercise-media/step-in-shot-put-throw/1.jpg"
    ],
    "instructions": [
      "Assume a semisquat stance with a medicine ball in your hands. Your arms should hang so the ball is near your feet.",
      "Begin by thrusting the hips forward as you extend through the legs, jumping up.",
      "As you do, swing your arms up and over your head, keeping them extended, releasing the ball at the peak of your movement. The goal is to throw the ball the greatest distance behind you."
    ],
    "primaryMuscles": [
      "shoulders"
    ]
  },
  "suitcase carry": {
    "name": "Suitcase carry",
    "slug": "suitcase-carry",
    "frames": [
      "/exercise-media/suitcase-carry/0.jpg",
      "/exercise-media/suitcase-carry/1.jpg"
    ],
    "instructions": [
      "Position the frame at the starting point, and load with the appropriate weight. Standing in the center of the frame, begin by gripping the handles and driving through your heels to lift the frame. Ensure your chest and head are up and your back is straight.",
      "Immediately begin walking briskly with quick, controlled steps. Keep your chest up and head forward, and make sure you continue breathing. Bring the frame to the ground after you have reached the end point."
    ],
    "primaryMuscles": [
      "forearms"
    ]
  },
  "towel row or rope row": {
    "name": "Towel row or rope row",
    "slug": "towel-row-or-rope-row",
    "frames": [
      "/exercise-media/towel-row-or-rope-row/0.jpg",
      "/exercise-media/towel-row-or-rope-row/1.jpg"
    ],
    "instructions": [
      "For this exercise you will need access to a low pulley row machine with a V-bar. Note: The V-bar will enable you to have a neutral grip where the palms of your hands face each other. To get into the starting position, first sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked.",
      "Lean over as you keep the natural alignment of your back and grab the V-bar handles.",
      "With your arms extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. You should be feeling a nice stretch on your lats as you hold the bar in front of you. This is the starting position of the exercise.",
      "Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it until you touch the abdominals. Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard. Hold that contraction for a second and slowly go back to the original position while breathing in.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "middle back"
    ]
  },
  "trap-bar deadlift": {
    "name": "Trap-bar deadlift",
    "slug": "trap-bar-deadlift",
    "frames": [
      "/exercise-media/trap-bar-deadlift/0.jpg",
      "/exercise-media/trap-bar-deadlift/1.jpg"
    ],
    "instructions": [
      "For this exercise load a trap bar, also known as a hex bar, to an appropriate weight resting on the ground. Stand in the center of the apparatus and grasp both handles.",
      "Lower your hips, look forward with your head and keep your chest up.",
      "Begin the movement by driving through the heels and extend your hips and knees. Avoid rounding your back at all times.",
      "At the completion of the movement, lower the weight back to the ground under control."
    ],
    "primaryMuscles": [
      "quadriceps"
    ]
  },
  "trap-bar deadlift or clean pull": {
    "name": "Trap-bar deadlift or clean pull",
    "slug": "trap-bar-deadlift-or-clean-pull",
    "frames": [
      "/exercise-media/trap-bar-deadlift-or-clean-pull/0.jpg",
      "/exercise-media/trap-bar-deadlift-or-clean-pull/1.jpg"
    ],
    "instructions": [
      "For this exercise load a trap bar, also known as a hex bar, to an appropriate weight resting on the ground. Stand in the center of the apparatus and grasp both handles.",
      "Lower your hips, look forward with your head and keep your chest up.",
      "Begin the movement by driving through the heels and extend your hips and knees. Avoid rounding your back at all times.",
      "At the completion of the movement, lower the weight back to the ground under control."
    ],
    "primaryMuscles": [
      "quadriceps"
    ]
  },
  "trap-bar or hinge pattern": {
    "name": "Trap-bar or hinge pattern",
    "slug": "trap-bar-or-hinge-pattern",
    "frames": [
      "/exercise-media/trap-bar-or-hinge-pattern/0.jpg",
      "/exercise-media/trap-bar-or-hinge-pattern/1.jpg"
    ],
    "instructions": [
      "For this exercise load a trap bar, also known as a hex bar, to an appropriate weight resting on the ground. Stand in the center of the apparatus and grasp both handles.",
      "Lower your hips, look forward with your head and keep your chest up.",
      "Begin the movement by driving through the heels and extend your hips and knees. Avoid rounding your back at all times.",
      "At the completion of the movement, lower the weight back to the ground under control."
    ],
    "primaryMuscles": [
      "quadriceps"
    ]
  },
  "two med-ball throw variations": {
    "name": "Two med-ball throw variations",
    "slug": "two-med-ball-throw-variations",
    "frames": [
      "/exercise-media/two-med-ball-throw-variations/0.jpg",
      "/exercise-media/two-med-ball-throw-variations/1.jpg"
    ],
    "instructions": [
      "Assume a semisquat stance with a medicine ball in your hands. Your arms should hang so the ball is near your feet.",
      "Begin by thrusting the hips forward as you extend through the legs, jumping up.",
      "As you do, swing your arms up and over your head, keeping them extended, releasing the ball at the peak of your movement. The goal is to throw the ball the greatest distance behind you."
    ],
    "primaryMuscles": [
      "shoulders"
    ]
  },
  "unilateral lower": {
    "name": "Unilateral lower",
    "slug": "unilateral-lower",
    "frames": [
      "/exercise-media/unilateral-lower/0.jpg",
      "/exercise-media/unilateral-lower/1.jpg"
    ],
    "instructions": [
      "Position yourself into a staggered stance with the rear foot elevated and front foot forward.",
      "Hold a dumbbell in each hand, letting them hang at the sides. This will be your starting position.",
      "Begin by descending, flexing your knee and hip to lower your body down. Maintain good posture througout the movement. Keep the front knee in line with the foot as you perform the exercise.",
      "At the bottom of the movement, drive through the heel to extend the knee and hip to return to the starting position."
    ],
    "primaryMuscles": [
      "quadriceps"
    ]
  },
  "weighted neutral-grip pull-up": {
    "name": "Weighted neutral-grip pull-up",
    "slug": "weighted-neutral-grip-pull-up",
    "frames": [
      "/exercise-media/weighted-neutral-grip-pull-up/0.jpg",
      "/exercise-media/weighted-neutral-grip-pull-up/1.jpg"
    ],
    "instructions": [
      "Attach a weight to a dip belt and secure it around your waist. Grab the pull-up bar with the palms of your hands facing forward. For a medium grip, your hands should be spaced at shoulder width. Both arms should be extended in front of you holding the bar at the chosen grip.",
      "You'll want to bring your torso back about 30 degrees while creating a curvature in your lower back and sticking your chest out. This will be your starting position.",
      "Now, exhale and pull your torso up until your head is above your hands. Concentrate on squeezing yourshoulder blades back and down as you reach the top contracted position.",
      "After a brief moment at the top contracted position, inhale and slowly lower your torso back to the starting position with your arms extended and your lats fully stretched."
    ],
    "primaryMuscles": [
      "lats"
    ]
  },
  "weighted pull-up": {
    "name": "Weighted pull-up",
    "slug": "weighted-pull-up",
    "frames": [
      "/exercise-media/weighted-pull-up/0.jpg",
      "/exercise-media/weighted-pull-up/1.jpg"
    ],
    "instructions": [
      "Attach a weight to a dip belt and secure it around your waist. Grab the pull-up bar with the palms of your hands facing forward. For a medium grip, your hands should be spaced at shoulder width. Both arms should be extended in front of you holding the bar at the chosen grip.",
      "You'll want to bring your torso back about 30 degrees while creating a curvature in your lower back and sticking your chest out. This will be your starting position.",
      "Now, exhale and pull your torso up until your head is above your hands. Concentrate on squeezing yourshoulder blades back and down as you reach the top contracted position.",
      "After a brief moment at the top contracted position, inhale and slowly lower your torso back to the starting position with your arms extended and your lats fully stretched."
    ],
    "primaryMuscles": [
      "lats"
    ]
  },
  "weighted pull-up or chin-up": {
    "name": "Weighted pull-up or chin-up",
    "slug": "weighted-pull-up-or-chin-up",
    "frames": [
      "/exercise-media/weighted-pull-up-or-chin-up/0.jpg",
      "/exercise-media/weighted-pull-up-or-chin-up/1.jpg"
    ],
    "instructions": [
      "Attach a weight to a dip belt and secure it around your waist. Grab the pull-up bar with the palms of your hands facing forward. For a medium grip, your hands should be spaced at shoulder width. Both arms should be extended in front of you holding the bar at the chosen grip.",
      "You'll want to bring your torso back about 30 degrees while creating a curvature in your lower back and sticking your chest out. This will be your starting position.",
      "Now, exhale and pull your torso up until your head is above your hands. Concentrate on squeezing yourshoulder blades back and down as you reach the top contracted position.",
      "After a brief moment at the top contracted position, inhale and slowly lower your torso back to the starting position with your arms extended and your lats fully stretched."
    ],
    "primaryMuscles": [
      "lats"
    ]
  },
}

export function getExerciseMedia(exerciseName: string): ExerciseMedia | null {
  const key = exerciseName.trim().toLowerCase()
  return EXERCISE_MEDIA[key] ?? null
}
