/**
 * Dev-only: parses the source .xlsx workbooks in data/source and emits
 * supabase/seed.sql. Run with: npm run seed:gen
 */
import { readdir } from 'node:fs/promises'
import { writeFileSync } from 'node:fs'
import * as fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import * as XLSX from 'xlsx'

XLSX.set_fs(fs)

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const sourceDir = join(root, 'data', 'source')
const outFile = join(root, 'supabase', 'seed.sql')

type CellValue = string | number | null
type Grid = CellValue[][]

function coerce(v: unknown): CellValue {
  if (v === null || v === undefined) return null
  if (typeof v === 'number' || typeof v === 'string') return v
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  if (v instanceof Date) return v.toISOString().slice(0, 10)
  return String(v)
}

function readGrid(ws: XLSX.WorkSheet): Grid {
  const rows = XLSX.utils.sheet_to_json<unknown[]>(ws, {
    header: 1,
    raw: true,
    defval: null,
    blankrows: true,
  })
  return rows.map((row) => (Array.isArray(row) ? row.map(coerce) : []))
}

function str(v: CellValue): string {
  return v === null ? '' : String(v).trim()
}

function findHeaderIndex(grid: Grid, firstHeader: string): number {
  return grid.findIndex((row) => str(row[0]) === firstHeader)
}

function sqlStr(v: CellValue): string {
  const s = str(v)
  if (s === '') return 'null'
  return `'${s.replace(/'/g, "''")}'`
}

function sqlNum(v: CellValue): string {
  if (v === null) return 'null'
  const n = typeof v === 'number' ? v : Number.parseFloat(str(v).replace(',', '.'))
  return Number.isFinite(n) ? String(n) : 'null'
}

function dayCode(dayLabel: CellValue): string {
  return str(dayLabel).charAt(0).toUpperCase()
}

function transferOnly(notes: CellValue): CellValue {
  const s = str(notes)
  if (s === '') return null
  const idx = s.indexOf('| Weekly focus')
  return idx >= 0 ? s.slice(0, idx).trim() : s
}

function loadWorkbook(file: string): XLSX.WorkBook {
  return XLSX.readFile(join(sourceDir, file), { cellDates: false })
}

function sheetByIncludes(wb: XLSX.WorkBook, needle: string): XLSX.WorkSheet | undefined {
  const name = wb.SheetNames.find((n) => n.toLowerCase().includes(needle.toLowerCase()))
  return name ? wb.Sheets[name] : undefined
}

const lines: string[] = []
lines.push('-- AUTO-GENERATED by scripts/generate-seed.ts. Do not edit by hand.')
lines.push('-- Reseed with: npm run seed:gen')
lines.push('')

async function main() {
  const files = (await readdir(sourceDir)).filter((f) => f.endsWith('.xlsx')).sort()
  const overviewFile = files.find((f) => f.startsWith('00'))
  const blockFiles = files.filter((f) => /^0[1-5]/.test(f)).sort()

  if (!overviewFile) throw new Error('Overview workbook (00 ...) not found in data/source')

  // ---- blocks (from overview Annual Overview) ----
  const overviewWb = loadWorkbook(overviewFile)
  const annual = sheetByIncludes(overviewWb, 'Annual Overview')
  if (!annual) throw new Error('Annual Overview sheet missing')
  const annualGrid = readGrid(annual)
  const annualHeader = findHeaderIndex(annualGrid, 'Block')

  lines.push('-- blocks')
  for (let i = annualHeader + 1; i < annualGrid.length; i++) {
    const row = annualGrid[i]
    const id = Number.parseInt(str(row[0]), 10)
    if (!Number.isFinite(id)) continue
    const title = str(row[2]).replace(/\.xlsx$/i, '')
    lines.push(
      `insert into blocks (id, title, weeks_label, primary_goal, day_a, day_c, day_b, hard_sets_range) values (` +
        `${id}, ${sqlStr(title)}, ${sqlStr(row[1])}, ${sqlStr(row[3])}, ${sqlStr(row[4])}, ${sqlStr(row[5])}, ${sqlStr(row[6])}, ${sqlStr(row[7])});`,
    )
  }
  lines.push('')

  // ---- weekly_calendar (overview) ----
  const cal = sheetByIncludes(overviewWb, 'Weekly Calendar')
  if (cal) {
    const grid = readGrid(cal)
    const h = findHeaderIndex(grid, 'Day')
    lines.push('-- weekly_calendar')
    let order = 0
    for (let i = h + 1; i < grid.length; i++) {
      const row = grid[i]
      if (str(row[0]) === '') continue
      lines.push(
        `insert into weekly_calendar (sort_order, day, training, session, intensity_rule, notes) values (` +
          `${order}, ${sqlStr(row[0])}, ${sqlStr(row[1])}, ${sqlStr(row[2])}, ${sqlStr(row[3])}, ${sqlStr(row[4])});`,
      )
      order++
    }
    lines.push('')
  }

  // ---- global_rules (overview) ----
  const glob = sheetByIncludes(overviewWb, 'Global Rules')
  if (glob) {
    const grid = readGrid(glob)
    const h = findHeaderIndex(grid, 'Priority')
    lines.push('-- global_rules')
    for (let i = h + 1; i < grid.length; i++) {
      const row = grid[i]
      if (str(row[1]) === '') continue
      lines.push(
        `insert into global_rules (priority, rule, implementation) values (` +
          `${sqlNum(row[0])}, ${sqlStr(row[1])}, ${sqlStr(row[2])});`,
      )
    }
    lines.push('')
  }

  // ---- per-block content ----
  for (const file of blockFiles) {
    const blockId = Number.parseInt(file.slice(0, 2), 10)
    const wb = loadWorkbook(file)

    const dash = sheetByIncludes(wb, 'Dashboard')
    if (dash) {
      const grid = readGrid(dash)
      const h = findHeaderIndex(grid, 'Week')
      lines.push(`-- program_weeks (block ${blockId})`)
      for (let i = h + 1; i < grid.length; i++) {
        const row = grid[i]
        const wkNum = Number.parseInt(str(row[0]), 10)
        if (!Number.isFinite(wkNum)) continue
        lines.push(
          `insert into program_weeks (week_number, block_id, focus, day_a_main, day_b_main, day_c_focus, hard_sets, main_rpe) values (` +
            `${wkNum}, ${blockId}, ${sqlStr(row[1])}, ${sqlStr(row[2])}, ${sqlStr(row[3])}, ${sqlStr(row[4])}, ${sqlNum(row[5])}, ${sqlNum(row[6])});`,
        )
      }
      lines.push('')
    }

    const plan = sheetByIncludes(wb, 'Plan')
    if (plan) {
      const grid = readGrid(plan)
      const h = findHeaderIndex(grid, 'Week')
      lines.push(`-- prescriptions (block ${blockId})`)
      const seq = new Map<string, number>()
      for (let i = h + 1; i < grid.length; i++) {
        const row = grid[i]
        const wkNum = Number.parseInt(str(row[0]), 10)
        if (!Number.isFinite(wkNum)) continue
        const label = row[1]
        const code = dayCode(label)
        const key = `${wkNum}|${code}`
        const order = seq.get(key) ?? 0
        seq.set(key, order + 1)
        lines.push(
          `insert into prescriptions (block_id, week_number, day_code, day_label, exercise, prescription, target_rpe, rest, transfer, sort_order) values (` +
            `${blockId}, ${wkNum}, ${sqlStr(code)}, ${sqlStr(label)}, ${sqlStr(row[2])}, ${sqlStr(row[3])}, ${sqlStr(row[4])}, ${sqlStr(row[5])}, ${sqlStr(transferOnly(row[8]))}, ${order});`,
        )
      }
      lines.push('')
    }

    const lib = sheetByIncludes(wb, 'Exercise Library')
    if (lib) {
      const grid = readGrid(lib)
      const h = findHeaderIndex(grid, 'Day')
      lines.push(`-- exercise_library (block ${blockId})`)
      let order = 0
      for (let i = h + 1; i < grid.length; i++) {
        const row = grid[i]
        if (str(row[1]) === '') continue
        lines.push(
          `insert into exercise_library (block_id, day_code, day_label, exercise, default_prescription, rpe, rest, transfer, sort_order) values (` +
            `${blockId}, ${sqlStr(dayCode(row[0]))}, ${sqlStr(row[0])}, ${sqlStr(row[1])}, ${sqlStr(row[2])}, ${sqlStr(row[3])}, ${sqlStr(row[4])}, ${sqlStr(row[5])}, ${order});`,
        )
        order++
      }
      lines.push('')
    }

    const prog = sheetByIncludes(wb, 'Progression Rules')
    if (prog) {
      const grid = readGrid(prog)
      const h = findHeaderIndex(grid, 'Rule')
      lines.push(`-- progression_rules (block ${blockId})`)
      let order = 0
      for (let i = h + 1; i < grid.length; i++) {
        const row = grid[i]
        if (str(row[0]) === '') continue
        lines.push(
          `insert into progression_rules (block_id, rule, implementation, sort_order) values (` +
            `${blockId}, ${sqlStr(row[0])}, ${sqlStr(row[1])}, ${order});`,
        )
        order++
      }
      lines.push('')
    }
  }

  writeFileSync(outFile, lines.join('\n'))
  const inserts = lines.filter((l) => l.startsWith('insert')).length
  console.log(`Wrote ${outFile} with ${inserts} insert statements.`)
}

main().catch((err: unknown) => {
  console.error(err)
  process.exit(1)
})
